### ISSUE TITLE
New apply method doesn't work with Flatpak

### ISSUE THREAD

**Issue by xenithorb** [mallowigi/slack-one-dark-theme#11]
Where the slack application is located at: `/var/lib/flatpak/app/com.slack.Slack` instead

```
  ____  _            _      _____ _                              _                _ _           
 / ___|| | __ _  ___| | __ |_   _| |__   ___ _ __ ___   ___     / \   _ __  _ __ | (_) ___ _ __ 
 \___ \| |/ _` |/ __| |/ /   | | | '_ \ / _ \ '_ ` _ \ / _ \   / _ \ | '_ \| '_ \| | |/ _ \ '__|
  ___) | | (_| | (__|   <    | | | | | |  __/ | | | | |  __/  / ___ \| |_) | |_) | | |  __/ |   
 |____/|_|\__,_|\___|_|\_\   |_| |_| |_|\___|_| |_| |_|\___| /_/   \_\ .__/| .__/|_|_|\___|_|   
                                                                     |_|   |_|                  
Welcome to the Slack Theme Applier CLI!

Please note that this is still experimental and can ruin your Slack application! In the case of a problem, please reinstall Slack.

? Please select an command Apply theme
Adding One Dark Theme Code to Slack... 

(node:11133) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, copyfile '/usr/lib/slack/resources/app.asar' -> '/usr/lib/slack/resources/app.asar.backup'
    at Object.copyFileSync (fs.js:1728:3)
    at Object.exports.apply (/home/xenithorb/git/slack-one-dark-theme/lib/command.js:39:6)
    at exports.execute (/home/xenithorb/git/slack-one-dark-theme/lib/command.js:67:12)
    at main (/home/xenithorb/git/slack-one-dark-theme/main.js:19:3)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11133) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by xenithorb** [comment]
The location of `app.asar` for example is:
```
/var/lib/flatpak/app/com.slack.Slack/x86_64/stable/dd864e4fc3d1eab1c29930e1f913bbc83c88cfdaa805a09e088b495563977703/files/extra/lib/slack/resources/app.asar
```

**Comment by xenithorb** [comment]
It looks `ssb-interop.js` no longer exists here. I switched `LINUX_DIR` to be `/var/lib/flatpak/app/com.slack.Slack/x86_64/stable/dd864e4fc3d1eab1c29930e1f913bbc83c88cfdaa805a09e088b495563977703/files/extra/lib/slack/resources` but it made no difference

```
(node:17531) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/var/lib/flatpak/app/com.slack.Slack/x86_64/stable/dd864e4fc3d1eab1c29930e1f913bbc83c88cfdaa805a09e088b495563977703/files/extra/lib/slack/resources/app.asar.unpacked/src/static/ssb-interop.js'
```

**Comment by mallowigi** [comment]
They updated slack and apparently changed the way it worked.
Just when I was rewriting from scratch... :disappointed

**Comment by mallowigi** [comment]
https://slack.engineering/rebuilding-slack-on-the-desktop-308d6fe94ae4?source=collection_home---4------0-----------------------&gi=37d81d672375
